"""The budget rules on the nodes: notices, the delegation cutoff and the
start of the wind-down (``runtime/time_rules.py`` holds the thresholds and the
notice text; ``nodes/wind_down.py`` runs the wind-down).

Every budget the config sets counts at once; the schedule keys on the one
furthest along. Only the entry node holds the run clock (``_run_start``); every
other node reaches it through ``_time_entry``. The same code serves every node
and both backends. A timer thread per threshold fires the wall notice even when
the entry node sits in one long CLI turn; a model call that ends moves the
token count; a poll reads the evaluation count from the store. The checkpoints
call the same idempotent tick, so a late timer or poll changes nothing.
"""
from __future__ import annotations

import threading
from pathlib import Path
from typing import Any

from ..infra import pending_notices, token_clock, wind_down
from ..runtime import constraint_snapshot
from ..runtime import time_rules as _rules
from .stop import _LIVE

EVAL_POLL_S = 5.0


class TimeRulesMixin:
    # ── the clock ────────────────────────────────────────────────────────────

    def _time_entry(self) -> Any | None:
        """The node that holds the run clock, from any node."""
        for n in self._stop_nodes():
            if n._run_start is not None and n._time_rules_ensure() is not None:
                return n
        return None

    def _time_rules_ensure(self) -> Any | None:
        """The rules for this node's clock, built once from the settings."""
        if (self._time_rules is None and self._run_start is not None
                and not self._silent):
            self._time_rules = _rules.TimeRules.from_settings(
                self._budget_seconds, token_clock.budget(),
                getattr(self, "_eval_budget", None))
        return self._time_rules

    def _time_progress(self, entry: Any) -> _rules.Progress:
        """How far each budget that is set has run: wall seconds since the run
        start, output tokens generated by every node, and evaluations in the
        canonical store."""
        rules = entry._time_rules
        return rules.progress(
            _rules.now() - entry._run_start,
            token_clock.used(),
            constraint_snapshot.evals_for_node(entry) if rules.evals else 0)

    def _time_rules_start(self) -> None:
        """Entry node, once per run: read the rules and arm what each budget
        needs: one timer per threshold on the wall budget, a listener on the
        token count, a poll of the store on the evaluation count."""
        if self._time_armed:
            return
        rules = self._time_rules_ensure()
        if rules is None:
            return
        self._time_armed = True
        if rules.tokens:
            token_clock.on_change(self._time_tokens_changed)
        if rules.evals:
            self._time_poll_arm()
        if rules.wall:
            for phase, _frac in rules.schedule():
                delay = self._run_start + rules.wall_at(phase) - _rules.now()
                self._time_timer_start(max(delay, 0.0) + 0.2,
                                       self._time_timer_fire)

    def _time_timer_start(self, delay: float, fn: Any) -> None:
        t = threading.Timer(delay, fn)
        t.daemon = True
        with self._time_lock:
            self._time_timers = [x for x in self._time_timers if x.is_alive()]
            self._time_timers.append(t)
        t.start()

    def _time_poll_arm(self) -> None:
        self._time_timer_start(EVAL_POLL_S, self._time_poll)

    def _time_poll(self) -> None:
        """Read the evaluation count and tick; look again until the
        wind-down has begun."""
        if self._time_closed:
            return
        self._time_timer_fire()
        if _rules.WIND_DOWN not in self._time_fired and not self._time_closed:
            self._time_poll_arm()

    def _time_tokens_changed(self) -> None:
        """A model call ended on some thread: if it crossed a threshold, fire
        it on its own thread so that thread's model call is not held up."""
        rules = self._time_rules
        if rules is None or self._time_closed:
            return
        with self._time_lock:
            new = [p for p in rules.due(self._time_progress(self).fraction)
                   if p not in self._time_fired]
        if new:
            t = threading.Thread(target=self._time_timer_fire, daemon=True)
            t.start()

    def _time_timer_fire(self) -> None:
        try:
            self._time_rules_tick()
        except Exception:  # noqa: BLE001
            pass

    def _time_rules_cancel(self) -> None:
        """The run is over: no timer may act on a later run in this process."""
        self._time_closed = True
        token_clock.remove_listener(self._time_tokens_changed)
        wind_down.end()
        with self._time_lock:
            timers, self._time_timers = self._time_timers, []
        for t in timers:
            t.cancel()

    def _time_elapsed(self) -> _rules.Progress | None:
        entry = self._time_entry()
        if entry is None or entry._run_start is None:
            return None
        return self._time_progress(entry)

    # ── the thresholds ───────────────────────────────────────────────────────

    def _time_rules_tick(self) -> None:
        """Fire every threshold the clock has passed, once. Idempotent.

        When several are due at once (a late checkpoint, a resume) only the
        latest fires: its notice states the rule that holds now.
        """
        entry = self._time_entry()
        if entry is None:
            return
        if entry is not self:
            entry._time_rules_tick()
            return
        rules = self._time_rules_ensure()
        if rules is None or self._time_closed:
            return
        prog = self._time_progress(self)
        with self._time_lock:
            due = [p for p in rules.due(prog.fraction)
                   if p not in self._time_fired]
            self._time_fired.update(due)
        if due:
            self._time_fire(due[-1], prog)

    def _time_fire(self, phase: str, prog: _rules.Progress) -> None:
        from ..runtime import features

        rules = self._time_rules
        if phase == _rules.WIND_DOWN:
            self._record_intervention(
                "TIME_WIND_DOWN", "(run)",
                f"{rules.budget_phrase()} reached: the wind-down begins",
                fault="observation")
            self._wind_down_begin(prog)
            return
        self._record_intervention(
            "TIME_" + phase.split(":")[0].upper(), "(run)",
            rules.notice(phase, prog, can_call_done=self._holds("Done")),
            fault="observation")
        if features.enabled("budget_notes"):
            self._time_broadcast(phase, prog)

    def _time_broadcast(self, phase: str, prog: _rules.Progress) -> None:
        """The notice to the entry node and to every running delegation."""
        rules = self._time_rules
        entry_text = rules.notice(
            phase, prog, can_call_done=self._holds("Done"))
        worker_text = rules.notice(phase, prog, can_call_done=False)
        with self._notifications_lock:
            self._notifications.append(f"[TIME — {entry_text}]")
        run_dir = self._current_run_dir
        if run_dir is None:
            return
        for n in self._stop_nodes():
            with n._registry_lock:
                live = [d for d, e in n._registry.items()
                        if e.get("status") in _LIVE]
            for did in live:
                pending_notices.post(
                    Path(run_dir) / "debug", did, f"[TIME — {worker_text}]")

    def _time_cutoff_refusal(self) -> str | None:
        """The ``Delegate`` refusal once the cutoff has passed, on any node.

        Always enforced when a budget is declared; ``budget_notes`` only
        decides whether the earlier notices are sent.
        """
        entry = self._time_entry()
        if entry is None:
            return None
        rules = entry._time_rules
        prog = self._time_progress(entry)
        if prog.fraction < rules.fraction_of(_rules.CUTOFF):
            return None
        text = rules.cutoff_refusal(prog, can_call_done=self._holds("Done"))
        self._record_intervention(
            "DELEGATE_CUTOFF", "(refused)",
            "new delegation refused: " + text, fault="observation")
        return "ERROR: " + text
